name: ci
on: push
jobs:
  test:
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
      - name: Switch Xcode to 11.3
        run: xcversion select 11.3
      - name: Resolve package dependencies
        run: swift package resolve
      - name: Install elixir
        run: brew install elixir
      - name: Install hex
        run: mix local.hex --force
      - name: Install rebar3
        run: mix local.rebar --force
      - name: Get dependencies for example phoenix app
        run: mix deps.get
        working-directory: ./Tests/PhoenixTests/example
      - name: Build the example app
        run: mix compile
        working-directory: ./Tests/PhoenixTests/example
      - name: Test
        run: |
          cd Tests/PhoenixTests/example
          ( mix phx.server & )
          cd -
          sleep 7
          swift test --skip-update
