name: CI

on: push

jobs:
  test:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14
        run: sudo xcode-select -s /Applications/Xcode_14.1.app
      - name: Resolve package dependencies
        run: swift package resolve
      - name: Install elixir
        run: brew install elixir
      - name: Install hex
        run: mix local.hex --force
      - name: Install rebar3
        run: mix local.rebar --force
      - name: Get dependencies for Phoenix app
        run: mix deps.get
        working-directory: ./Tests/PhoenixTests/server
      - name: Build the server app
        run: mix compile
        working-directory: ./Tests/PhoenixTests/server
      - name: Test
        run: |
          cd Tests/PhoenixTests/server
          ( mix phx.server & )
          cd -
          sleep 7
          swift test --skip-update
